spring:
    security:
        oauth2:
            client:
                provider:
                    gateway:
                        issuer-uri: http://localhost:9000
                registration:
                    gateway:
                        authorization-grant-type: authorization_code
                        client-authentication-method: client_secret_basic
                        client-id: gateway
                        client-secret: secret
                        provider: gateway
                        redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
                        scope: openid
#logging:
#    level:
#        ROOT: DEBUG
#        reactor:
#            netty: DEBUG
#        org:
#            springframework:
#                security: DEBUG
#                cloud:
#                    gateway: DEBUG

#    cloud:
#        gateway:
#            httpclient:
#                wiretap: true
#            httpserver:
#                wiretap: true


eureka:
    instance:
        preferIpAddress: true
    client:
        fetchRegistry: true
        registerWithEureka: true
        serviceUrl:
            defaultZone: http://localhost:8072/eureka/
